baseURL = "/"
languageCode = "en"
title = "Porrith Suong"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Porrith Suong"
  description = "In solitude, where we are least alone."
  github = "psuong"
  twitter = "PorrithSuong"
  linkedin = "PorrithSuong"
  email = "porrith.suong@gmail.com"
  url = "https://psuong.github.io"
  keywords = "blog, google analytics"
  rss = false
  lastmod = false
  location = "New York"
  userStatusEmoji = ""

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
